//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deceased
    {
        public int Deceased_Id { get; set; }
        public string DeceasedPerson { get; set; }
        public string DeceasedCnic { get; set; }
        public string ReasonOfDeath { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
