//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentCard
    {
        public int Id { get; set; }
        public string CardNumber { get; set; }
        public bool Active { get; set; }
        public string Name { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string cvc { get; set; }
    }
}
