//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase()
        {
            this.PurchaseDetails = new HashSet<PurchaseDetail>();
        }
    
        public int Id { get; set; }
        public Nullable<int> PurchaseNo { get; set; }
        public string ReferenceNumber { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public int VendorId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public int Status { get; set; }
        public Nullable<int> QutotationReferenceNo { get; set; }
        public Nullable<int> GR { get; set; }
        public Nullable<System.DateTime> DocumnetDate { get; set; }
        public Nullable<System.DateTime> PostingDate { get; set; }
        public bool IsReturned { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseDetail> PurchaseDetails { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
