//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockLog
    {
        public int Id { get; set; }
        public Nullable<int> MaterailId { get; set; }
        public string MaterailName { get; set; }
        public Nullable<int> StockIn { get; set; }
        public Nullable<int> StockOut { get; set; }
        public Nullable<int> Status { get; set; }
        public string Description { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
