//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAction_Log
    {
        public int ID { get; set; }
        public Nullable<int> UserLogId { get; set; }
        public string UserAction { get; set; }
        public Nullable<System.DateTime> ActionDate { get; set; }
    
        public virtual Users_Log Users_Log { get; set; }
    }
}
