//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MangoERP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        public int Vendor_ID { get; set; }
        public string Vendor_Name { get; set; }
        public string Contact_Person { get; set; }
        public string Vendor_Contact { get; set; }
        public string Vendor_Payment_Type { get; set; }
    }
}
